### ISSUE TITLE
@camunda8/operate calls wrong endpoint for flownodes methods

### ISSUE THREAD

**Issue by ershov-konst** [camunda-community-hub/camunda-8-js-sdk#50]
## SDK Component

Operate

## Expected Behavior

The following methods work
- `searchFlownodeInstances`
- `getFlownodeInstance`

## Current Behavior

It looks like methods don't call correct endpoints
- `searchFlownodeInstances` calls the `flownodes/search` but should call the `flownode-instances/search`
- `getFlownodeInstance` calls the `flownodes/${key}` but should call the `flownode-instances/${key}`

## Context (Environment)

`"@camunda8/operate": "^8.4.0"`

**Comment by jwulf** [comment]
Thanks for reporting this. I will take a look at this next week. 

If you want to submit a PR for, this is the code base to do it.

**Comment by jwulf** [comment]
This is addressed by: https://github.com/camunda-community-hub/camunda-8-js-sdk/pull/82

It will come out in 8.5.0 of @camunda8/sdk
